Web/Web/Models/ErrorViewModel.cs
using System;

namespace Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web/Web/ViewModels/OrderDetailViewModel.cs
namespace Web.ViewModels
{
    public class OrderDetailViewModel
    {
        public int OrderDetailId { get; set; }
        public byte[] FaceData { get; set; }
        public string ImageString { get; set; }
    }
}

Web/Web/ViewModels/OrderListViewModel.cs
using System.Collections.Generic;

namespace Web.ViewModels
{
    public class OrderListViewModel
    {
        public List<OrderViewModel> Orders { get; set; }
    }
}

Web/Web/ViewModels/OrderViewModel.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;

namespace Web.ViewModels
{
    public class OrderViewModel
    {
        [Display(Name ="Order Id")]
        public Guid OrderId { get; set; }

        [Display(Name ="Email")]
        public string UserEmail { get; set; }

        [Display(Name ="Image File")]
        public IFormFile File { get; set; }

        [Display(Name ="PictureUrl")]
        public string PictureUrl { get; set; }

        [Display(Name ="Order Status")]
        public string Status { get; set; }

        public byte[] ImageData { get; set; }
        public string ImageString { get; set; }
        public List<OrderDetailViewModel> OrderDetails { get; set; }
    }
}

Web/Web/Controllers/HomeController.cs
using System;
using System.IO;
using Web.Models;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Messaging.InterfacesConstants.Commands;
using Messaging.InterfacesConstants.Constants;
using MassTransit;
using Web.ViewModels;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IBusControl _busControl;
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger, IBusControl busControl)
        {
            _logger = logger;
            _busControl = busControl;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult RegisterOrder()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> RegisterOrder(OrderViewModel model)
        {
            var memory = new MemoryStream();

            await using (var uploadedFile = model.File.OpenReadStream())
            {
                await uploadedFile.CopyToAsync(memory);
            }

            model.ImageData = memory.ToArray();
            model.OrderId = Guid.NewGuid();
            model.PictureUrl = model.File.FileName;

            var sendToUri = new Uri($"{RabbitMqMassTransitConstants.RabbitMqUri}" +
                                    $"{RabbitMqMassTransitConstants.RegisterOrderCommandQueue}");

            var endPoint = await _busControl.GetSendEndpoint(sendToUri);
            
            await endPoint.Send<IRegisterOrderCommand>(
                new
                {
                    model.OrderId,
                    model.UserEmail,
                    model.ImageData,
                    model.PictureUrl
                });
            
            ViewData["OrderId"] = model.OrderId;
            
            return View("Thanks");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

Web/Web/Controllers/OrderManagementController.cs
using System;
using Web.RestClients;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class OrderManagementController : Controller
    {
        private readonly IOrderManagementApi _orderManagementApi;

        public OrderManagementController(IOrderManagementApi orderManagementApi)
        {
            _orderManagementApi = orderManagementApi;
        }

        public async Task<IActionResult> Index()
        {
            var orders = await _orderManagementApi.GetOrders();

            foreach (var order in orders)
            {
                order.ImageString = ConvertAndFormatToString(order.ImageData);
            }

            return View(orders);
        }


        [Route("/Details/{orderId}")]
        public async Task<IActionResult> Details(string orderId)
        {
            var order = await _orderManagementApi.GetOrderById(Guid.Parse(orderId));

            order.ImageString = ConvertAndFormatToString(order.ImageData);

            foreach (var detail in order.OrderDetails)
            {
                detail.ImageString = ConvertAndFormatToString(detail.FaceData);
            }

            return View(order);
        }

        private string ConvertAndFormatToString(byte[] imageData)
        {
            var imageBase64Data = Convert.ToBase64String(imageData);

            return $"data:image/png;base64, {imageBase64Data}";
        }
    }
}

Web/Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

Web/Web/Views/Home/RegisterOrder.cshtml
@model Web.ViewModels.OrderViewModel
@{
    ViewData["Title"] = "Register order page";
}

<div>
    <img src="~/image/logo.jpg" width="300" alt="img"/>
    <h2>Order Registration</h2>
</div>
<form asp-controller="Home" asp-action="RegisterOrder" enctype="multipart/form-data">
    <div class="row">
        <div class="col-md-10">
            <h3>Enter your emial address and upload your faces picture</h3>
            <div class="form-group">
                <label asp-for="UserEmail"></label>
                <input asp-for="UserEmail" class="form-control"/>
            </div>
        </div>
        <div class="col-md-10">
            <p>Upload your image file using the button below</p>
            <input type="file" name="file"/>
        </div>
    </div>
    <input type="submit" class="btn btn-info" value="Submit"/>
</form>

Web/Web/Views/Home/Thanks.cshtml
@{
    ViewData["Title"] = "Thanks";
}

<h2>Thank you formaction your order. You will be notified as the processing of the order progresses.</h2>
<h2> Your OrderId: @ViewData["OrderId"] </h2>

Web/Web/Views/OrderManagement/Details.cshtml
@model Web.ViewModels.OrderViewModel
@{
    ViewData["Title"] = "Order Details";
}
<h3>Order Details</h3>
Order Id: @Model.OrderId
User Email: @Model.UserEmail
Picture:
<img src="@Model.ImageString" width="100px" height="100px" alt="image"/>
Order Status: @Model.Status
<table class="table">
    <thead>
    <tr>
        <th>OrderDetailId</th>
        <th>Image</th>
    </tr>
    </thead>
    <tbody>

    @foreach (var detail in Model.OrderDetails)
    {
        <tr>
            <td>@detail.OrderDetailId</td>
            <td>
                <img src="@detail.ImageString" width="40px" height="40px" alt="image"/>
            </td>
        </tr>
    }
    </tbody>
</table>

Web/Web/Views/OrderManagement/Index.cshtml
@model List<Web.ViewModels.OrderViewModel>
@using Microsoft.Extensions.Options
@inject IOptions<Setting> settings
@{
    ViewData["Title"] = "Orders List";
}
<h3>Orders Management - overview</h3>
<table class="table">
    <thead>
    <tr>
        <th>Order Id</th>
        <th>User Email</th>
        <th>Image</th>
        <th>Status</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var order in Model)
    {
        <tr class="clickable"
            onclick="location.href='@Url.Action("Details", "OrderManagement", new {orderId = order.OrderId})'">
            <td>@order.OrderId</td>
            <td>@order.UserEmail</td>
            <td>
                <img src="@order.ImageString" width="50px" height="50px" alt="image"/>
            </td>
            <td>@order.Status</td>


        </tr>
    }
    </tbody>


</table>

@section Scripts
{
    <script src="~/lib/signalr/dist/browser/signalr.js"></script>
    <script type="text/javascript">
             let timerId;
             const connection = new signalR.HubConnectionBuilder()
                 .withUrl('@settings.Value.SignalRHubUrl/orderhub')
                 .configureLogging(signalR.LogLevel.Debug)
                 .withAutomaticReconnect()
                 .build();
    
             connection.on('UpdateOrders', (message, orderId) => {
    
                 //const encodedMsg = message + ":" + orderId;
                 
                 if (orderId && orderId.length) {
                     toastr.success(orderId + ' Updated to status' + message);
                     refreshPage();
                 }
             });
    
             function refreshPage() {
                 clearTimeout(timerId);
                 timerId = setTimeout(function () {
                     window.location.reload();
                 }, 1000)
             }
    
             connection.start()
             .catch(err =>
                console.error(err.toString())
             );
    </script>
}

Web/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="RegisterOrder">RegisterOrder</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="OrderManagement" asp-action="Index">Orders List</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/lib/toastr.js/toastr.min.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>